"""update relationship

Revision ID: 475752af5912
Revises: e3d9b29e9bd2
Create Date: 2022-04-24 21:57:46.262030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475752af5912'
down_revision = 'e3d9b29e9bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'athletes', ['team_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'athletes', type_='unique')
    # ### end Alembic commands ###
